//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GelGit1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int KullaniciID { get; set; }
        public string İsim { get; set; }
        public string Soyİsim { get; set; }
        public bool AracDurumu { get; set; }
        public string Parola { get; set; }
        public string UserName { get; set; }
    
        public virtual KullaniciArac KullaniciArac { get; set; }
        public virtual Kullaniciİletisim Kullaniciİletisim { get; set; }
        public virtual KullaniciOkulB KullaniciOkulB { get; set; }
        public virtual KullaniciPuani KullaniciPuani { get; set; }
    }
}
