//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GelGit1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciOkulB
    {
        public int OkulBID { get; set; }
        public string OkulNo { get; set; }
        public string Bolumu { get; set; }
        public string OkulAdi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
