//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GelGit1.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gelgitdtbsEntities : DbContext
    {
        public gelgitdtbsEntities()
            : base("name=gelgitdtbsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KullaniciArac> KullaniciArac { get; set; }
        public virtual DbSet<Kullaniciİletisim> Kullaniciİletisim { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<KullaniciOkulB> KullaniciOkulB { get; set; }
        public virtual DbSet<KullaniciPuani> KullaniciPuani { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yolcular> Yolcular { get; set; }
        public virtual DbSet<YolculukDetaylari> YolculukDetaylari { get; set; }
        public virtual DbSet<Yolculuklar> Yolculuklar { get; set; }
    }
}
