//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GelGit1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yolcular
    {
        public int YolculukID { get; set; }
        public int YolcuID { get; set; }
        public int ID { get; set; }
    
        public virtual Yolculuklar Yolculuklar { get; set; }
    }
}
