//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GelGit1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yolculuklar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yolculuklar()
        {
            this.Yolcular = new HashSet<Yolcular>();
        }
    
        public int YolculukID { get; set; }
        public int SurucuID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yolcular> Yolcular { get; set; }
        public virtual YolculukDetaylari YolculukDetaylari { get; set; }
    }
}
