//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GelGit1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YolculukDetaylari
    {
        public int YolculukDetayID { get; set; }
        public System.DateTime KalkisZamani { get; set; }
        public string KalkisNoktasi { get; set; }
        public string VarisNoktasi { get; set; }
        public byte Ucret { get; set; }
        public string SurucuMesaji { get; set; }
    
        public virtual Yolculuklar Yolculuklar { get; set; }
    }
}
